version: '3.7'

services:
  ef_storage:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'quorum_db'
      POSTGRES_USER: 'quorum_user'
      POSTGRES_PASSWORD: 'quorum_password'
    networks: 
      quorum_network:
        ipv4_address: 172.20.20.2

  api:
    build: 
      dockerfile: Docker/api.dockerfile
      context: ../
    networks: 
      quorum_network:
        ipv4_address: 172.20.20.3
    depends_on: 
      - ef_storage
        
  client:
    build:
      dockerfile: Docker/client.dockerfile
      context: ../
    networks:
      quorum_network:
        ipv4_address: 172.20.20.4
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ../Client/nginx.conf:/etc/nginx/nginx.conf:ro
      
networks: 
  quorum_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
      - subnet: 172.20.20.0/24
