export * from "./app/app.component";
export * from "./home/home.component";
export * from "./header/header.component";
export * from "./new-test/new-test.component";
export * from "./sign-in/sign-in.component";
export * from "./sign-up/sign-up.component";
export * from "./menu-button/menu-button.component";
export * from "./test-polygon/test-polygon.component";
export * from "./leave-confirmation-dialog/leave-confirmation-dialog.component";
