// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quorum.DataAccess.Ef;

namespace Quorum.DataAccess.Ef.Migrations
{
    [DbContext(typeof(EfDataAccessContext))]
    [Migration("20190416202212_FixIdGeneration")]
    partial class FixIdGeneration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("IsCorrect");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.PassedAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCorrect");

                    b.Property<int?>("PassedQuestionId");

                    b.Property<int>("SourceAnswerId");

                    b.HasKey("Id");

                    b.HasIndex("PassedQuestionId");

                    b.HasIndex("SourceAnswerId");

                    b.ToTable("PassedAnswers");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.PassedQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PassedTestId");

                    b.Property<int>("SourceQuestionId");

                    b.HasKey("Id");

                    b.HasIndex("PassedTestId");

                    b.HasIndex("SourceQuestionId");

                    b.ToTable("PassedQuestions");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.PassedTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TimeSpent");

                    b.HasKey("Id");

                    b.ToTable("PassedTests");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int?>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TimeLimit");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Answer", b =>
                {
                    b.HasOne("Quorum.BusinessCore.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.PassedAnswer", b =>
                {
                    b.HasOne("Quorum.BusinessCore.Entities.PassedQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("PassedQuestionId");

                    b.HasOne("Quorum.BusinessCore.Entities.Answer", "SourceAnswer")
                        .WithMany()
                        .HasForeignKey("SourceAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.PassedQuestion", b =>
                {
                    b.HasOne("Quorum.BusinessCore.Entities.PassedTest")
                        .WithMany("Questions")
                        .HasForeignKey("PassedTestId");

                    b.HasOne("Quorum.BusinessCore.Entities.Question", "SourceQuestion")
                        .WithMany()
                        .HasForeignKey("SourceQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Question", b =>
                {
                    b.HasOne("Quorum.BusinessCore.Entities.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quorum.BusinessCore.Entities.Tag", b =>
                {
                    b.HasOne("Quorum.BusinessCore.Entities.Test")
                        .WithMany("Tags")
                        .HasForeignKey("TestId");
                });
#pragma warning restore 612, 618
        }
    }
}
